name: Transcripto
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  assemblyai_flutter_sdk: ^0.0.10
  connectivity_plus: ^6.1.4
  flutter:
    sdk: flutter
  flutter_gemini: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  http: ^1.4.0
  just_audio: ^0.10.2
  logger: ^2.5.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  youtube_explode_dart: ^2.4.0
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/transcripto.png
    - assets/words/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/transcripto.png"
  adaptive_icon_background: "#6F83F0" # Optional: Background color for Android adaptive icons
  min_sdk_android: 21 # Optional: Minimum Android SDK version
